# Generated by Django 3.1.2 on 2021-06-16 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='id_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='id_product',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='productreview',
            name='mark',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
    ]
