# Generated by Django 3.1.2 on 2021-06-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0004_auto_20210628_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpositions',
            old_name='id_order',
            new_name='order',
        ),
    ]
