# Generated by Django 3.1.2 on 2021-06-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0007_auto_20210628_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
