# Generated by Django 3.1.2 on 2021-06-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'Измерение', 'verbose_name_plural': 'Измерения'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
    ]
